Began arm code
FRC3636/bunnybots-2024 pull request #1
Opened 2024-11-13 01:19 UTC by Taimorioka

2024-11-14 04:25 UTC, doinkythederp requested changes

2024-11-14 04:25 UTC, doinkythederp commented on src/main/java/com/frcteam3636/frc2024/subsystems/arm/ArmIO.kt
> +            private var leftCurrent = Volts.zero()!!
```suggestion
            var leftCurrent = Volts.zero()!!
```
for consistency

2024-11-14 04:25 UTC, doinkythederp commented on src/main/java/com/frcteam3636/frc2024/subsystems/arm/ArmIO.kt
> +        override fun setPosition(position: Measure<Angle>) {
i think it would be good to call this something else - like "pivotToPosition" - because this could be confused with setting the encoder offset

2024-11-14 04:25 UTC, doinkythederp commented on src/main/java/com/frcteam3636/frc2024/subsystems/arm/ArmIO.kt
> +            leftMotor.setControl(leftControl)
let's rename this to `control` because it needs to be used for both left and right motors

2024-11-14 04:25 UTC, doinkythederp commented on src/main/java/com/frcteam3636/frc2024/subsystems/arm/ArmIO.kt
> +            leftMotor.setControl(leftControl)
Also,
```suggestion
            leftMotor.setControl(leftControl)
            rightMotor.setControl(leftControl)
```

2024-11-16 16:37 UTC, rezetta15 commented on src/main/java/com/frcteam3636/frc2024/subsystems/arm/ArmIO.kt
> +            val control = VoltageOut(volts.`in`(Volts))
Seems prudent to bounds check the input Voltage value in case SysID loses its mind.

2024-11-20 01:14 UTC, doinkythederp approved these changes

2024-11-20 01:15 UTC, merged